### ISSUE TITLE
Files missing in dependency generator

### ISSUE THREAD

**Issue by jeffng-or** [The-OpenROAD-Project/bazel-orfs#100]
The following files are missing from the files exported in dependency generation (bazel run myDesign_floorplan_deps -- <absolute_path>):

1. flow/util/generate-vars.sh
2. flow/util/makeIssue.sh
3. tools/install/yosys

**Comment by oharboe** [comment]
@jeffng-or Why should ORFS/tools/yosys be included? That's a source folder...

**Comment by jeffng-or** [comment]
Sorry, that should be tools/install/yosys, not tools/yosys.

To get around https://github.com/The-OpenROAD-Project/bazel-orfs/issues/99, I hacked the "make" file to point to tools/install/yosys/bin/yosys. But, when I actually ran the "make floorplan_issue" command, it still couldn't find yosys since tools/install/yosys wasn't in the expected location.

**Comment by oharboe** [comment]
@jeffng-or Use your local ORFS build for now, run `. env.sh`, then invoke `build/make foo_issue`.

I'll investigate more tomorrow.

**Comment by maliberty** [comment]
Do we need the yosys binary?  In general 'make issue' test cases are OR issues and we don't need to re-run synthesis.

**Comment by oharboe** [comment]
> Do we need the yosys binary? In general 'make issue' test cases are OR issues and we don't need to re-run synthesis.

Yes, if you are re-running the synthesis stage, you do. If you are creating a `make issue`, no. I've fixed it here: https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/pull/2249

**Comment by oharboe** [comment]
@jeffng-or This is how it fits together, waiting for confirmation from @hovind before merging: https://github.com/The-OpenROAD-Project/bazel-orfs/pull/108
