### ISSUE TITLE
Unit tests for bazel-orfs?

### ISSUE THREAD

**Issue by jeffng-or** [The-OpenROAD-Project/bazel-orfs#106]
Is it possible to add unit tests for bazel-orfs?

**Comment by oharboe** [comment]
Interesting question, never heard about such a thing... Would be useful. We do have some CI integration tests at least...

**Comment by oharboe** [comment]
Let's ask around, meanwhile, closing this issue since we can't do anything now. Easy to reopen.

**Comment by jeffng-or** [comment]
Found this in my research: https://bazel.build/rules/testing. There is a unit testing framework to test out rules.

**Comment by oharboe** [comment]
I don't see any immediate actions here, we'll try to go with what we have for now unless we see something specific and narrow we can improve.
