### ISSUE TITLE
Rename generated "make" file to non-conflicting name?

### ISSUE THREAD

**Issue by jeffng-or** [The-OpenROAD-Project/bazel-orfs#107]
When we run:

bazel run <design>_<stage>_deps `pwd`/build

it generates a "make" script in `pwd`/build. And then we execute `pwd`/build/make do-<stage> to run. Inside of the "make" script, it then calls the make executable.

Can we name "make" to something else? I realize that we don't run into execution issues because "make" ends up calling make and not itself. But, it would be certainly easier to describe problems with the "make" file vs. a problem with the Makefile that make calls as a resut of calling "make". :-)

**Comment by oharboe** [comment]
I like make. Simple and the user is expected to add ORFS make options aftewards on the command line.

I'm open to suggestions though.

**Comment by oharboe** [comment]
Please refer to it as "The make wrapper" in all future communication :-)

**Comment by jeffng-or** [comment]
Sounds good!
