### ISSUE TITLE
Add CI test case and docs for mock proprietary PDK

### ISSUE THREAD

**Issue by oharboe** [The-OpenROAD-Project/bazel-orfs#50]
A proprietary PDK comes as a .tar.gz file or similar from the foundry. PLATFORM_DIR is an environment variable that can be made to point to a proprietary PDK in ORFS.

Tasks:

- [ ] Make a .tar.gz. of orfs/platforms/asap7, untar it somewhere and test that ORFS(without bazel-orfs) can use it. Verify by something like `make PLATFORM_DIR=path-to-untarred-asap7 designs/asap7/gcd/config.mk` works.
- [ ] Choose a suitable bazel friendly way to upload in a github repository or google cloud repository 
- [ ] Create a CI test case in bazel-orfs that uses the .tar.gz file

@lpawelcz @tmichalak @maliberty Reasonable?

**Comment by lpawelcz** [comment]
Opened https://github.com/The-OpenROAD-Project/bazel-orfs/pull/56 with base support for external PDKs and two examples for local testing

**Comment by tmichalak** [comment]
@oharboe should we focus on finishing this task?

**Comment by oharboe** [comment]
No, leave be for now.
