### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by maliberty** [The-OpenROAD-Project/bazel-orfs#98]
In https://github.com/The-OpenROAD-Project/bazel-orfs?tab=readme-ov-file#requirements the link https://github.com/The-OpenROAD-Project/bazel-orfs/blob/main/MODULE.bzl should be https://github.com/The-OpenROAD-Project/bazel-orfs/blob/main/MODULE.bazel

**Comment by oharboe** [comment]
Fixed
